### ISSUE TITLE
[EPIC] Align DB structure to TrinityCore

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1118]
_Note: I'm opening this in order to finish the work previously started here_: https://github.com/azerothcore/azerothcore-wotlk/issues/236 

This is an **epic** task that groups all the tasks needed to upgrade the **structure of the AzerothCore Databases** in order to make it  as close as possible to the one of [TrinityCore 3.3.5](https://github.com/TrinityCore/TrinityCore/tree/3.3.5).

## Benefits

- **Documentation**. Currently we have no official DB documentation. We could just copy and reuse the same [DB documentation from tc](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/74663833/World+3.3.5) once this task is completed (this is already the case for many tables, but for some of them the structure is different and it's undocumented).

- **Cross-project collaboration**. It will be easier to import any DB-content fixes that are pushed into the 3.3.5 branch of TrinityCore. Having a look at the [commit history](https://github.com/TrinityCore/TrinityCore/commits/3.3.5) of that branch, you can notice that there are still several contributors that push DB fixes periodically.

- **Tooling**. AzerothCore would benefit of all existing tooling currently available for TC 3.3.5. For example the [JSON API](https://github.com/FrancescoBorzi/TC-JSON-API) and all the tools that rely on it (such as [Keira2 DB editor](https://github.com/Helias/Keira2) and many other tools like [those](https://github.com/FrancescoBorzi?tab=repositories&q=trinitycore)).

- **Migration**. It would be much easier for server administrators to migrate from TrinityCore to AzerothCore.

- **Simplicity**. The new structure simplifies many things, for example the huge `quest_template` table has being split into several smaller ones.

_**Personal note**: I believe a big part of this job has been already done, and it's worth to finish it. Also it looks like that there is no intention in TrinityCore to change the 3.3.5 DB structure anymore. So once we finish this, we can only benefit_

### World DB

- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1119 Simplify the `quest_template` table
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1120 Update structure of the `*_loot_template` tables
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1178 Misc minor changes
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1179 Locale changes
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1182 Creature movement
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1177 `achievement_reward`
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1180 `creature`
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1181 `creature_template`
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1183 `gameobject`
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1184 `gameobject_addon`
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1185 `gameobject_overrides`
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1186 `gameobject_template`
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1187 `game_event`
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1189 `graveyard_zone`
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1190 `instance_spawn_groups`
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1191 `playercreateinfo_*`
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1192 `player_factionchange_*`
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1193 `points_of_interest`
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1313 `quest_greeting`
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1328 `quest_template_addon`
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1195 `skill_extra_item_template`
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1196 `skill_perfect_item_template`
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1197 `smart_scripts`
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1198 `spawn_group*`
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1199 `spell_enchant_proc_data`
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1200 `spell_group`
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1201 `spell_learn_spell`
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1202 `spell_proc_*`

### Characters DB

- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1125 Add `itemcount5` and `itemcount6` fields in `character_queststatus`
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1176 Implement Quest Tracker
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1165 `auctionbidders` (new table)
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1239 `auctionhouse`
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1166 `channels`
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1167 `character_arena_stats` 
- ~~https://github.com/azerothcore/azerothcore-wotlk/issues/1168 `character_aura` & `pet_aura`~~ _Pondaveia: due to spells being different from AC to TC I suggest leaving this change off due to issues with the pull request on TC aswell._
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1169 `character_fishingsteps` (new table)
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1170 `character_instance` 
- https://github.com/azerothcore/azerothcore-wotlk/issues/1171 ~~`character_spell`, `character_spell_cooldown` & `pet_spell_cooldown`~~ **NOT APPLICABLE**
- https://github.com/azerothcore/azerothcore-wotlk/issues/1172 ~~`character_talent`~~ **NOT APPLICABLE**
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1173 `group_instance` (new table)
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1174 `item_loot_items` (different table)
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1175 `item_loot_money` (new table)

### Auth

- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1162 Import `logs_ip_actions` table and feature
- https://github.com/azerothcore/azerothcore-wotlk/issues/1121 ~~Import RBAC system~~ **DEFERRED**
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/1163 Table `account` minor changes

## How to spot the original commits that made the diff

Finding the commits is quite easy for most of the diff, read this: https://github.com/azerothcore/azerothcore-wotlk/wiki/How-to-spot-db-struct-diff-commits

### Diffs

I extracted most of the diff from:

- [Auth DB diff](https://gist.github.com/FrancescoBorzi/c98de2e92f757e0a202ead4dd040cc7b)
- [Characters DB diff](https://gist.github.com/FrancescoBorzi/f83b9502c97ea2f42207d1c1de8f9d1b)
- [World DB diff](https://gist.github.com/FrancescoBorzi/31e0a5b238e509ab0233a8d02ca54d84)

**Comment by StygianTheBest** [comment]
Do you have a breakdown of all the database changes?

**Comment by FrancescoBorzi** [comment]
**UPDATE**: we can extract further tasks from the DB diffs:

- [Auth DB diff](https://gist.github.com/FrancescoBorzi/c98de2e92f757e0a202ead4dd040cc7b)
- [Characters DB diff](https://gist.github.com/FrancescoBorzi/f83b9502c97ea2f42207d1c1de8f9d1b)
- [World DB diff](https://gist.github.com/FrancescoBorzi/31e0a5b238e509ab0233a8d02ca54d84)

**Comment by BarbzYHOOL** [comment]
it's still WIP?

**Comment by FrancescoBorzi** [comment]
All the most important changes have been imported. There are still a few ones left but AFAIK no one is working on them. This can be left open and visible to whoever wants to import more changes.

**Comment by BarbzYHOOL** [comment]
because we could also put the "big list to import" as pinned issue

**Comment by Yehonal** [comment]
can we close this issue? is kinda useless.

We should only import certain changes to the table when we need certain fields. But keeping our DB in sync with TC is a limitation for us since it means that we cannot adapt our DB to our needs to avoid breaking the compatibility with TC

**Comment by FrancescoBorzi** [comment]
yeah I think we have already migrated most of the ones which made sense to migrate and if someone still finds something specific that can be aligned, that can always be accepted, but no need to keep an epic open for this

**Comment by Aztec2012** [comment]
Any news?
