### ISSUE TITLE
[EPIC] Align SmartAI to TrinityCore

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1326]
This will make easy to exchange SmartAI scripts between AzerothCore and TrinityCore

### Global
- [x] Add missing fields in the table

### Event
- There are some minor difference in Events, shouldn't be an issue. But feel free to investigate.

### Action
- [x] Move `SMART_ACTION_SET_SIGHT_DIST` to `121`
- [x] Move `SMART_ACTION_FLEE` to `122`
- [x] Move `SMART_ACTION_ADD_THREAT` to `123`
- [x] Move `SMART_ACTION_LOAD_EQUIPMENT` to `124`
- [x] Move `SMART_ACTION_TRIGGER_RANDOM_TIMED_EVENT` to `125`
- [x] Move `SMART_ACTION_REMOVE_ALL_GAMEOBJECTS` to `126`

- [x] Remove the remaining extra overlap in enum (after the moves above)

- [x] Reserve missing enums, display proper error if someone tries to use them

- [x] `SMART_ACTION_ADD_QUEST` -> `SMART_ACTION_OFFER_QUEST` https://github.com/TrinityCore/TrinityCore/commit/ba4d6f63936fe3269e6c8b75358bc00a78fd49df
- [x] Add param3 to SMART_ACTION_CAST and SMART_ACTION_INVOKER_CAST (but be careful since we already have a param3 there, so maybe add that as param4 ?) https://github.com/TrinityCore/TrinityCore/commit/9072e0221b39c19fb6be154c623f45d6a9433db0
- [x] Get rid of unused parameter 'storageId' (third) in SMART_ACTION_SUMMON_CREATURE https://github.com/TrinityCore/TrinityCore/commit/a5c248b60ffd4981f6f62bc0640b4fcf1321a8c3
- [x] Reserve smart action 16 https://github.com/TrinityCore/TrinityCore/commit/4e55e797532ca404ce0e1e603762c17ead760f45
- [x] Core/Scripts: Extended SMART_ACTION_SET_INST_DATA to also set BossStates. https://github.com/TrinityCore/TrinityCore/commit/d1d0c64ad11cb3faf986a5332fec6b704fb8026c
- [ ] (Optional) cleaning https://github.com/TrinityCore/TrinityCore/commit/84bff76ba054683ca497b8b758cb86728d5f52a2
- [ ] Solve enum conflict `SMART_ACTION_SET_DATA` vs `SMART_ACTION_MOVE_FORWARD` 
- [ ] Rename `SMART_ACTION_SET_FLY` to `SMART_ACTION_SET_DISABLE_GRAVITY` (part of this big commit of Xinef1 https://github.com/TrinityCore/TrinityCore/commit/b0ae5fadd19fd172ec5154cde4f4fd14aa20ff88)
- [x] Add missing parameters for `SMART_ACTION_MOVE_TO_POS` (this and probably others too: https://github.com/TrinityCore/TrinityCore/commit/60d1c0e20d3f8f32de81bff047531b927e586a97)
- [ ] Solve `SMART_ACTION_ENABLE_TEMP_GOBJ` vs `SMART_ACTION_RESPAWN_TARGET` enum conflict
- [x] Replace `SMART_ACTION_INVOKER_CAST` with `SMART_ACTION_SELF_CAST` in action `85`. `SMART_ACTION_INVOKER_CAST` moves to `134` https://github.com/TrinityCore/TrinityCore/commit/0df3cb5bcc8097070b1f215032d3914d6a577f01
- [ ] Investigate how `SMART_ACTION_JUMP_TO_POS` parameters differ
- [ ] Investigate how `SMART_ACTION_SET_HOME_POS` parameter is different

- [ ] Add missing actions (some of them from the same big commit of Xinef1 mentioned above https://github.com/TrinityCore/TrinityCore/commit/b0ae5fadd19fd172ec5154cde4f4fd14aa20ff88)

### Target
- [x] Move `SMART_TARGET_FARTHEST` to `28`
- [x] Reserve missing enums, display proper error if someone tries to use them
- [x] Implement `SMART_TARGET_LOOT_RECIPIENTS`
- [x] Implement `SMART_TARGET_VEHICLE_PASSENGER`

- There are more minor differences in Targets, feel free to investigate them.

**Comment by Pondaveia** [comment]
> Get rid of unused parameter 'storageId' (third) in SMART_ACTION_SUMMON_CREATURE 
Checked this and we no longer have storageId

**Comment by gengarshadowball** [comment]
What is ACTION_MOVE_TO_POS parameter 4 (ContactDistance) used for? Do we need this?

**Comment by P-Kito** [comment]
> 
> 
> What is ACTION_MOVE_TO_POS parameter 4 (ContactDistance) used for? Do we need this?

Check if it is used in DB, but I suppose there is some cases which use this parameter.
It will make u move to a position but with a distance to it.

**Comment by FrancescoBorzi** [comment]
the best place to find out is checking the core source code and see what that parameter is actually doing

**Comment by Kitzunu** [comment]
After discussions with the Guru Mr. SAI Master @Gultask, this issue is no longer needed.
