### ISSUE TITLE
[EPIC] Align conditions to TrintiyCore

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1372]
This will make easy to exchange `conditions` between AzerothCore and TrinityCore

https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130002/conditions#conditions-ConditionTypeOrReference

### ConditionTypes

- [x] Solve conflicts and prevent unsupported `ConditionTypes` to be used
- [x] Allow CONDITION_OBJECT_ENTRY to check for object guid https://github.com/TrinityCore/TrinityCore/commit/2a36d2bf5b7f14284a499a14f476c4633b1fc0eb
- [x] Implement `CONDITION_STAND_STATE`
- [x] Implement `CONDITION_DAILY_QUEST_DONE`
- [x] Implement `CONDITION_CHARMED` https://github.com/azerothcore/azerothcore-wotlk/issues/731
- [x] Implement `CONDITION_PET_TYPE`
- [x] Implement `CONDITION_TAXI`
- [x] Implement `CONDITION_QUESTSTATE`

### ConditionSourceType
- [x] Solve conflicts and prevent unsupported `ConditionSourceType`(s) to be used
- [x] Merge `CONDITION_SOURCE_TYPE_QUEST_SHOW_MARK` and `CONDITION_SOURCE_TYPE_QUEST_ACCEPT` into `CONDITION_SOURCE_TYPE_QUEST_AVAILABLE` and mark `20` as unused.
  - https://github.com/TrinityCore/TrinityCore/commit/95f2aedb5a24a7c198c24747a04a5d60ff800fd2
  - https://github.com/TrinityCore/TrinityCore/commit/cef5d795a09a94f1b6dfc2788c4a379ce01a9ccd
  - https://github.com/TrinityCore/TrinityCore/commit/fe2db0731328e104ea9e8f5d7081e732c9f02e6f

**Comment by BarbzYHOOL** [comment]
ok we need this else can't fix some quests like Nefarius's Corruption failed loot reward

**Comment by BarbzYHOOL** [comment]
we might repin it? xD

**Comment by Helias** [comment]
```
 Merge CONDITION_SOURCE_TYPE_QUEST_SHOW_MARK and CONDITION_SOURCE_TYPE_QUEST_ACCEPT into CONDITION_SOURCE_TYPE_QUEST_AVAILABLE and mark 20 as unused.
```
Did @Kitzunu already did this here? https://github.com/azerothcore/azerothcore-wotlk/pull/2859

In case, check it

**Comment by claudiodfc** [comment]
Implement CONDITION_QUESTSTATE has been merged so maybe someone should tick that to avoid confusion 😄
