### ISSUE TITLE
EPIC: List of all missing features and relevant optimizations

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#20979]
## Describe your feature request or suggestion in detail

I'm proposing this topic so that we can keep track of notable improvements in AC outside the fix of current issues. In particular, I'd like to list a number of existing issues and evaluate the most relevant ones.

In particular, I propose two categories: missing features and major refactoring/optimization.

### Gameplay
- [x] [Sparring system](https://github.com/azerothcore/azerothcore-wotlk/issues/15849)
- [ ] Period grace
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/4355
- [ ] Tug of War
- [ ] A proper system for GCD with MindControls (https://github.com/azerothcore/azerothcore-wotlk/issues/19187 / https://github.com/azerothcore/azerothcore-wotlk/issues/11975)
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/9386

### Events
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/16256
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/1688

### Framework/Core
- [ ] Creature static flags
- [ ] Several spells attributes
- [ ] Creature secondary stats (https://github.com/azerothcore/azerothcore-wotlk/issues/19238)
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/12641
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/7786
- [ ] Cyclic paths

### Features:
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/4302
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/5704
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/11073
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/11072
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/8767
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/17912
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/18761

### Gameplay
- [ ] Move several current system into heartbeat
- [ ] Improve movement system (https://github.com/azerothcore/azerothcore-wotlk/issues/10096 for example)
- [ ] Improve pathfinding (https://github.com/azerothcore/azerothcore-wotlk/issues/18024)
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/20306
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/17683
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/5985

### SAI
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/16359
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/14939

### Core
- [ ] Finish to remove all hardcoded gossip
- [ ] Improve the codestyle and AC naming standards
- [ ] Throttling movements
- [ ] Improve Vmap and collision detection (https://github.com/azerothcore/azerothcore-wotlk/discussions/3971 + some 2024 commits in TC to improve Vmap)
- [ ] Map ressources usages to evaluate which part need to be improved for more performance
- [ ] Prepare to cpp-23 as default support
- [ ] Use more std::chrono

### DB 
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/16942

### Dependencies
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/9766

**Comment by Exitare** [comment]
IMO, the gamemgr has some places that could benefit from a refactoring as well e.g.  the LoadDB function

**Comment by fangshun2004** [comment]
Azerothcore also lacks a creature-following and respawn system like Cmangos and Vmangos. When the follower dies. Followers will randomly wander around. There are also followers who are reborn and will only appear in the respawn position

**Comment by Grimdhex** [comment]
> Azerothcore also lacks a creature-following and respawn system like Cmangos and Vmangos. When the follower dies. Followers will randomly wander around. There are also followers who are reborn and will only appear in the respawn position

Could you detail the feature of respawn system ? Maybe a like of few commit from mangos ?

**Comment by fangshun2004** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/8313
https://github.com/azerothcore/azerothcore-wotlk/issues/14274

**Comment by Nyeriah** [comment]
EPICS is a model we no longer use, in fact have not used at the time of this post. There are other features such as milestones instead, that help us manage things like this with more ease. Closing

**Comment by Helias** [comment]
We could convert this as milestone indeed
