### ISSUE TITLE
Database Structure Update TODO list

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#236]
It would be nice to keep the Database Structure and SOAP Interface compatible with latest versions of TrinityCore as much as possible. Offering a legacy interface for TC Soap for example.
This to allow developers to create external tools and sql mods that can easily communicate/work for both server applications.

# DataBase structure TODO list

### World database

- [ ] Update structure of the ``*_loot_template`` tables
- [x] Import massive World DB backport from TC-6.x to TC-3.3.5a [(done)](https://github.com/azerothcore/azerothcore-wotlk/pull/154)
- [x] Import https://github.com/TrinityCore/TrinityCore/commit/1c0b0f825c70c2fee8c3c5280e5015275056624e
- [ ] Import https://github.com/TrinityCore/TrinityCore/commit/5178395a4f973fdb0b9657e54f06e62a6e2d5111
- [ ] Import https://github.com/TrinityCore/TrinityCore/commit/b41e0156dbc084ec35603cb30492e0410eb697dd
- [ ] Import https://github.com/TrinityCore/TrinityCore/commit/bc67016e7bfe8ffcd7220897c44e4d49d1392834
- [ ] Import https://github.com/TrinityCore/TrinityCore/commit/f7c7b92ef3c7f600276495f6d28061716fba0c23
- [x] Import https://github.com/TrinityCore/TrinityCore/commit/33892e0f9da468e8aa3ea173e5baa269235e5070
- [x] Import https://github.com/TrinityCore/TrinityCore/commit/38cbefd3c4725a3b4ad24bd493299b7aaecc93c2
- [ ] Import https://github.com/TrinityCore/TrinityCore/commit/4a532a71b655945f394fecfe4a2177b2618a6d59
- [ ] Import https://github.com/TrinityCore/TrinityCore/commit/b1d773f3d50a45051066281f2e1c5f3407fd424c
- [ ] (....) check other possible diff that can be imported

### Characters database

- [x] Import massive Characters DB backports from TC-6.x to TC-3.3.5a [(done)](https://github.com/azerothcore/azerothcore-wotlk/pull/27)
- [x] Clear ``arena_team_member`` structure
- [x] Import playerBytes split from https://github.com/TrinityCore/TrinityCore/commit/1925778e44a370b26ae8f16b76279f62d20fb5be

- [ ] (....) check other possible diff that can be imported

### Auth database

- [x] Align ``account`` table
- [x] Import ``account_muted`` table and feature
- [ ] Import ``logs_ip_actions`` table and feature
- [x] Import ``uptime`` table and feature
- [x] Import ``ip2nation`` and ``ip2nationCountries`` tables and feature
- [ ] Import RBAC system

**Comment by HeartWell** [comment]
I forgot, all this comity was moved to Sunwell and worked perfectly.

And don't forget this. https://github.com/TrinityCore/TrinityCore/commit/1ddf44caf3b0c9af2cc4169b608f1801c2f6f52a

**Comment by Demonid** [comment]
I would suggest porting this too:

https://github.com/TrinityCore/TrinityCore/commit/1925778e44a370b26ae8f16b76279f62d20fb5be

Im converting a test DB from TC to AC and for now i only had 2 main issues.

1- Related to the PlayerBytes i linked above.
2- The way AC handles talents and spells is different from TC.

If this two things have the same structure, using a DB from TC should be really easy.

**Comment by ShinDarth** [comment]
@Demonid it's already in the TODO list :)

**Comment by ShinDarth** [comment]
@Demonid it's already in the TODO list :)

feel free to open a PR for it

**Comment by neltharionorg** [comment]
Uptime imported from trinitycore
https://github.com/neltharionorg/azerothcore-wotlk/commit/cfa426b90107a0e412a2c8df0353ca33e71d8a17

**Comment by ShinDarth** [comment]
@neltharionorg nice! please open a PR so we can import it to azerothcore
