### ISSUE TITLE
[EPIC] Load gossip texts from source to DB

### ISSUE THREAD

**Issue by LichKing255** [azerothcore/azerothcore-wotlk#2444]
Must move gossip texts from source to DB.This reduces size of Core and improves its performance.
I created a list that contains the exact file paths and Gossip names that you can easily find by searching the file.
There is no need to move them all at once and can be moved to several committees, anyone moving each one I will check that file in the list.

**List :**
- [ ]  scripts\EasternKingdoms\BlackrockMountain\BlackrockDepths\blackrock_depths.cpp
    -  #define GOSSIP_DUGHAL

- [ ]  scripts\EasternKingdoms\Karazhan\bosses_opera.cpp
    -  #define GOSSIP_GRANDMA

- [ ]  scripts\EasternKingdoms\Karazhan\karazhan.cpp 
    -  #define GOSSIP_READY

- [x]  scripts\EasternKingdoms\zone_loch_modan.cpp
    -  #define GOSSIP_MP
    -  #define GOSSIP_MP1
    -  #define GOSSIP_MP2
    -  #define GOSSIP_MP3
    -  #define GOSSIP_MP4
    -  #define GOSSIP_MP5
    -  #define GOSSIP_MP6

- [x]  scripts\EasternKingdoms\zone_stormwind_city.cpp
    -  #define GOSSIP_ITEM_KAT_1
    -  #define GOSSIP_ITEM_KAT_2
    -  #define GOSSIP_ITEM_KAT_3
    -  #define GOSSIP_ITEM_KAT_4

- [ ]  scripts\EasternKingdoms\zone_undercity.cpp
    -  #define GOSSIP_HPF1
    -  #define GOSSIP_HPF2
    -  #define GOSSIP_HPF3
    -  #define GOSSIP_WRYNN
    -  #define GOSSIP_THRALL

- [ ]  scripts\EasternKingdoms\zone_western_plaguelands.cpp
    -  #define GOSSIP_HDA1
    -  #define GOSSIP_HDA2
    -  #define GOSSIP_HDA3
    -  #define GOSSIP_HDA4
    -  #define GOSSIP_SDA1
    -  #define GOSSIP_ITEM_ILLUSION

- [ ]  scripts\EasternKingdoms\ZulAman\zulaman.cpp
    -  #define GOSSIP_HOSTAGE1

- [ ]  scripts\Events\brewfest.cpp
    -  #define GOSSIP_ITEM_COREN1
    -  #define GOSSIP_ITEM_COREN2

- [ ]  scripts\Kalimdor\CavernsOfTime\BattleForMountHyjal\hyjal.cpp
    -  #define GOSSIP_ITEM_BEGIN_ALLY
    -  #define GOSSIP_ITEM_ANETHERON
    -  #define GOSSIP_ITEM_BEGIN_HORDE
    -  #define GOSSIP_ITEM_AZGALOR
    -  #define GOSSIP_ITEM_RETREAT
    -  #define GOSSIP_ITEM_TYRANDE
    -  #define GOSSIP_ITEM_GM1

- [ ]  scripts\Kalimdor\CavernsOfTime\CullingOfStratholme\culling_of_stratholme.cpp
    -  #define GOSSIP_ITEM_ARTHAS_1
    -  #define GOSSIP_ITEM_ARTHAS_2
    -  #define GOSSIP_ITEM_ARTHAS_3
    -  #define GOSSIP_ITEM_ARTHAS_4
    -  #define GOSSIP_ITEM_ARTHAS_5
    -  #define GOSSIP_ITEM_ARTHAS_6

- [ ]  scripts\Kalimdor\zone_azshara.cpp
    -  #define GOSSIP_HELLO_LT1
    -  #define GOSSIP_HELLO_LT2
    -  #define GOSSIP_SELECT_LT1
    -  #define GOSSIP_SELECT_LT2
    -  #define GOSSIP_SELECT_LT3
    -  #define GOSSIP_SELECT_LT4
    -  #define GOSSIP_SELECT_LT5
    -  #define GOSSIP_GET_MOONSTONE

- [ ]  scripts\Kalimdor\zone_darkshore.cpp
    -  #define GOSSIP_ITEM_INSERT_KEY

- [ ]  scripts\Kalimdor\zone_dustwallow_marsh.cpp
    -  #define GOSSIP_ITEM_JAINA

- [ ]  scripts\Kalimdor\zone_felwood.cpp
    -  #define GOSSIP_ITEM_BEACON

- [ ]  scripts\Kalimdor\zone_feralas.cpp
    -  #define GOSSIP_HELLO

- [ ]  scripts\Kalimdor\zone_moonglade.cpp
    -  #define GOSSIP_ITEM_THUNDER
    -  #define GOSSIP_ITEM_AQ_END
    -  #define GOSSIP_BEAR1
    -  #define GOSSIP_BEAR2
    -  #define GOSSIP_BEAR3
    -  #define GOSSIP_BEAR4
    -  #define GOSSIP_ITEM_RUTHERAN
    -  #define GOSSIP_ITEM_AQ_AGI

- [ ]  scripts\Kalimdor\zone_orgrimmar.cpp
    -  #define GOSSIP_HTW
    -  #define GOSSIP_STW1
    -  #define GOSSIP_STW2
    -  #define GOSSIP_STW3
    -  #define GOSSIP_STW4
    -  #define GOSSIP_STW5
    -  #define GOSSIP_STW6

- [ ]  scripts\Kalimdor\zone_silithus.cpp
    -  #define GOSSIP_ITEM1
    -  #define GOSSIP_ITEM2
    -  #define GOSSIP_ITEM3
    -  #define GOSSIP_ITEM4
    -  #define GOSSIP_ITEM5
    -  #define GOSSIP_ITEM6
    -  #define GOSSIP_ITEM7
    -  #define GOSSIP_ITEM11
    -  #define GOSSIP_ITEM12
    -  #define GOSSIP_ITEM13
    -  #define GOSSIP_ITEM14
    -  #define GOSSIP_ITEM15
    -  #define GOSSIP_TEMPLAR_RANDOM
    -  #define GOSSIP_TEMPLAR_FIRE
    -  #define GOSSIP_TEMPLAR_EARTH
    -  #define GOSSIP_TEMPLAR_AIR
    -  #define GOSSIP_TEMPLAR_WATER
    -  #define GOSSIP_DUKE_RANDOM
    -  #define GOSSIP_DUKE_FIRE
    -  #define GOSSIP_DUKE_EARTH
    -  #define GOSSIP_DUKE_AIR
    -  #define GOSSIP_DUKE_WATER
    -  #define GOSSIP_ROYAL_RANDOM
    -  #define GOSSIP_ROYAL_FIRE
    -  #define GOSSIP_ROYAL_EARTH
    -  #define GOSSIP_ROYAL_AIR
    -  #define GOSSIP_ROYAL_WATER

- [ ]  scripts\Kalimdor\zone_stonetalon_mountains.cpp
    -  #define GOSSIP_HBD1
    -  #define GOSSIP_HBD2
    -  #define GOSSIP_HBD3
    -  #define GOSSIP_HBD4
    -  #define GOSSIP_HBD5

- [ ]  scripts\Kalimdor\zone_tanaris.cpp
    -  #define GOSSIP_ITEM_FLIGHT
    -  #define GOSSIP_ITEM_NORGANNON_1
    -  #define GOSSIP_ITEM_NORGANNON_2
    -  #define GOSSIP_ITEM_NORGANNON_3
    -  #define GOSSIP_ITEM_NORGANNON_4
    -  #define GOSSIP_ITEM_NORGANNON_5
    -  #define GOSSIP_ITEM_NORGANNON_6

- [ ]  scripts\Kalimdor\zone_the_barrens.cpp
    -  #define GOSSIP_CORPSE

- [ ]  scripts\Kalimdor\zone_thousand_needles.cpp
    -  #define GOSSIP_P

- [ ]  scripts\Kalimdor\zone_thunder_bluff.cpp
    -  #define GOSSIP_HCB

- [ ]  scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\trial_of_the_champion.cpp
    -  #define GOSSIP_HCB
    -  #define GOSSIP_START_EVENT1a
    -  #define GOSSIP_START_EVENT1b
    -  #define GOSSIP_START_EVENT2
    -  #define GOSSIP_START_EVENT3

- [ ]  scripts\Northrend\Nexus\Oculus\oculus.cpp
    -  #define GOSSIP_ITEM_DRAKES
    -  #define GOSSIP_ITEM_BELGARISTRASZ1
    -  #define GOSSIP_ITEM_BELGARISTRASZ2
    -  #define GOSSIP_ITEM_VERDISA1
    -  #define GOSSIP_ITEM_VERDISA2
    -  #define GOSSIP_ITEM_ETERNOS1
    -  #define GOSSIP_ITEM_ETERNOS2

- [ ]  scripts\Northrend\Ulduar\HallsOfStone\brann_bronzebeard.cpp
    -  #define GOSSIP_ITEM_1
    -  #define GOSSIP_ITEM_2
    -  #define GOSSIP_ITEM_3
    -  #define GOSSIP_ITEM_4

- [ ]  scripts\Northrend\VioletHold\violet_hold.cpp
    -  #define GOSSIP_START_EVENT
    -  #define GOSSIP_ITEM_1
    -  #define GOSSIP_I_WANT_IN

- [ ]  scripts\Northrend\zone_borean_tundra.cpp
    -  #define GOSSIP_ITEM_C_1

- [ ]  scripts\Northrend\zone_howling_fjord.cpp
    -  #define GOSSIP_RAZAEL_REPORT
    -  #define GOSSIP_LYANA_REPORT

- [ ]  scripts\Northrend\zone_sholazar_basin.cpp
    -  #define GOSSIP_VEKJIK_ITEM1
    -  #define GOSSIP_VEKJIK_ITEM2
    -  #define GOSSIP_ITEM_AOF1
    -  #define GOSSIP_ITEM_AOF2
    -  #define GOSSIP_ITEM_AOF3
    -  #define GOSSIP_OPTION_ORANGE
    -  #define GOSSIP_OPTION_BANANAS
    -  #define GOSSIP_OPTION_PAPAYA

- [ ]  scripts\Northrend\zone_wintergrasp.cpp
    -  #define GOSSIP_HELLO_DEMO1
    -  #define GOSSIP_HELLO_DEMO2
    -  #define GOSSIP_HELLO_DEMO3
    -  #define GOSSIP_HELLO_DEMO4

- [ ]  scripts\Outland\zone_netherstorm.cpp
    -  #define GOSSIP_ITEM

- [ ]  scripts\Outland\zone_shadowmoon_valley.cpp
    -  #define GOSSIP_HSK1
    -  #define GOSSIP_HSK2

- [ ]  scripts\Outland\zone_shattrath_city.cpp
    -  #define GOSSIP_RALIQ
    -  #define GOSSIP_HZ

- [ ]  scripts\Outland\zone_terokkar_forest.cpp
    -  #define GOSSIP_FLOON1
    -  #define GOSSIP_FLOON2
    -  #define GOSSIP_S_DARKSCREECHER_AKKARAI
    -  #define GOSSIP_S_KARROG
    -  #define GOSSIP_S_GEZZARAK_THE_HUNTRESS
    -  #define GOSSIP_S_VAKKIZ_THE_WINDRAGER

- [ ]  scripts\Outland\zone_zangarmarsh.cpp
    -  #define GOSSIP_ITEM_BLESS_ASH
    -  #define GOSSIP_ITEM_BLESS_KEL
    -  #define GOSSIP_COOSH
    -  #define GOSSIP_ITEM_KUR1
    -  #define GOSSIP_ITEM_KUR2
    -  #define GOSSIP_ITEM_KUR3
    -  #define GOSSIP_TIMOTHY_DANIEL
    -  #define GOSSIP_TEXT_BROWSE_POISONS

- [ ]  scripts\World\go_scripts.cpp
    -  #define GOSSIP_FEL_CRYSTALFORGE_ITEM_1
    -  #define GOSSIP_FEL_CRYSTALFORGE_ITEM_5
    -  #define GOSSIP_FEL_CRYSTALFORGE_ITEM_RETURN
    -  #define GOSSIP_BASHIR_CRYSTALFORGE_ITEM_1
    -  #define GOSSIP_BASHIR_CRYSTALFORGE_ITEM_5
    -  #define GOSSIP_BASHIR_CRYSTALFORGE_ITEM_RETURN
    -  #define GOSSIP_USE_OUTHOUSE

- [ ]  scripts\World\npcs_special.cpp
    -  #define GOSSIP_ITEM_GRANT
    -  #define GOSSIP_HELLO_SAYGE
    -  #define GOSSIP_SENDACTION_SAYGE1
    -  #define GOSSIP_SENDACTION_SAYGE2
    -  #define GOSSIP_SENDACTION_SAYGE3
    -  #define GOSSIP_SENDACTION_SAYGE4
    -  #define GOSSIP_SENDACTION_SAYGE5
    -  #define GOSSIP_SENDACTION_SAYGE6
    -  #define GOSSIP_SENDACTION_SAYGE7
    -  #define GOSSIP_SENDACTION_SAYGE8
    -  #define GOSSIP_SENDACTION_SAYGE9
    -  #define GOSSIP_SENDACTION_SAYGE10
    -  #define GOSSIP_SENDACTION_SAYGE11
    -  #define GOSSIP_SENDACTION_SAYGE12
    -  #define GOSSIP_SENDACTION_SAYGE13
    -  #define GOSSIP_SENDACTION_SAYGE14
    -  #define GOSSIP_SENDACTION_SAYGE15
    -  #define GOSSIP_SENDACTION_SAYGE16
    -  #define GOSSIP_SENDACTION_SAYGE17
    -  #define GOSSIP_ENGINEERING1
    -  #define GOSSIP_ENGINEERING2
    -  #define GOSSIP_ENGINEERING3
    -  #define GOSSIP_ENGINEERING4
    -  #define GOSSIP_ENGINEERING5
    -  #define GOSSIP_ENGINEERING6
    -  #define GOSSIP_LOST_ARCATRAZ_KEY
    -  #define GOSSIP_LOST_SHADOWFORGE_KEY
    -  #define GOSSIP_LOST_SKELETON_KEY
    -  #define GOSSIP_LOST_SHATTERED_HALLS_KEY
    -  #define GOSSIP_LOST_THE_MASTERS_KEY
    -  #define GOSSIP_LOST_VIOLET_HOLD_KEY
    -  #define GOSSIP_LOST_ESSENCE_INFUSED_MOONSTONE
    -  #define GOSSIP_LOST_KEY_TO_THE_FOCUSING_IRIS
    -  #define GOSSIP_LOST_HC_KEY_TO_THE_FOCUSING_IRIS
    -  #define GOSSIP_XP_OFF
    -  #define GOSSIP_XP_ON

- [ ]  scripts\World\npc_professions.cpp
    -  #define GOSSIP_LEARN_POTION
    -  #define GOSSIP_UNLEARN_POTION
    -  #define GOSSIP_LEARN_TRANSMUTE
    -  #define GOSSIP_UNLEARN_TRANSMUTE
    -  #define GOSSIP_LEARN_ELIXIR
    -  #define GOSSIP_UNLEARN_ELIXIR
    -  #define GOSSIP_WEAPON_LEARN
    -  #define GOSSIP_WEAPON_UNLEARN
    -  #define GOSSIP_ARMOR_LEARN
    -  #define GOSSIP_ARMOR_UNLEARN
    -  #define GOSSIP_UNLEARN_SMITH_SPEC
    -  #define GOSSIP_LEARN_HAMMER
    -  #define GOSSIP_UNLEARN_HAMMER
    -  #define GOSSIP_LEARN_AXE
    -  #define GOSSIP_UNLEARN_AXE
    -  #define GOSSIP_LEARN_SWORD
    -  #define GOSSIP_UNLEARN_SWORD
    -  #define GOSSIP_LEARN_DRAGON
    -  #define GOSSIP_LEARN_ELEMENTAL
    -  #define GOSSIP_LEARN_TRIBAL
    -  #define GOSSIP_LEARN_SPELLFIRE
    -  #define GOSSIP_UNLEARN_SPELLFIRE
    -  #define GOSSIP_LEARN_MOONCLOTH
    -  #define GOSSIP_UNLEARN_MOONCLOTH
    -  #define GOSSIP_LEARN_SHADOWEAVE
    -  #define GOSSIP_UNLEARN_SHADOWEAVE
    -  #define GOSSIP_LEARN_GOBLIN
    -  #define GOSSIP_LEARN_GNOMISH
    -  #define GOSSIP_UNLEARN_GOBLIN
    -  #define GOSSIP_UNLEARN_GNOMISH
    -  #define GOSSIP_ITEM_ZAP
    -  #define GOSSIP_ITEM_JHORDY
    -  #define GOSSIP_ITEM_KABLAM

- [ ]  scripts\World\npc_taxi.cpp
    -  #define GOSSIP_SUSURRUS
    -  #define GOSSIP_NETHER_DRAKE
    -  #define GOSSIP_IRONWING
    -  #define GOSSIP_DABIREE1
    -  #define GOSSIP_DABIREE2
    -  #define GOSSIP_WINDBELLOW1
    -  #define GOSSIP_WINDBELLOW2
    -  #define GOSSIP_BRACK1
    -  #define GOSSIP_BRACK2
    -  #define GOSSIP_BRACK3
    -  #define GOSSIP_IRENA
    -  #define GOSSIP_CLOUDBREAKER1
    -  #define GOSSIP_CLOUDBREAKER2
    -  #define GOSSIP_DRAGONHAWK
    -  #define GOSSIP_VERONIA
    -  #define GOSSIP_DEESAK
    -  #define GOSSIP_AFRASASTRASZ1
    -  #define GOSSIP_AFRASASTRASZ2
    -  #define GOSSIP_TARIOLSTRASZ1
    -  #define GOSSIP_TARIOLSTRASZ2
    -  #define GOSSIP_TORASTRASZA1
    -  #define GOSSIP_TORASTRASZA2
    -  #define GOSSIP_CRIMSONWING
    -  #define GOSSIP_WILLIAMKEILAR1
    -  #define GOSSIP_WILLIAMKEILAR2
    -  #define GOSSIP_WILLIAMKEILAR3
  
- [ ]   scripts/Northrend/FrozenHalls/ForgeOfSouls/forge_of_soulscpp
    -  npc_fos_leader

**Comment by gengarshadowball** [comment]
Update:
- blackrock_depths
( creature scripts are commented, are they useless or must be re-done?)
1. #define SAY_WINDSOR_AGGRO1
2. #define SAY_REGINALD_WINDSOR_0_1
3. #define SAY_TOBIAS_FREE

**Comment by TobiMiller** [comment]
please add to list:
forge of souls -> npc_fos_leader

**Comment by Kitzunu** [comment]
Going to close this as I made an issue per file
