### ISSUE TITLE
Remove ACE dependence [$300]

### ISSUE THREAD

**Issue by Winfidonarleyan** [azerothcore/azerothcore-wotlk#3451]
# TASK
- [x] `ASSERT` - #4950
- [x] `Configuration` - #4608
- [x] `Method_Request` - #3459
- [x] `Stack_Trace` #6574
- [x] `Task` #5454
- [x] `Guard_T` - #4821
- [x] `Event_Handler` (signal) - #4877
- [x] `Based` #6574
- [x] `TSS_T` #5454
- [x] `INET_Addr` #6574
- [x] `Reactor` #5679
- [x] `Acceptor` #6574
- [x] `Future` #5611
- [x] `Queue` #5611
- [x] `Basic_Types`
- [x] `Semaphore`  - #4951
- [x] `AutoPtr` - #3454
- [x] `OS_NS_time` - #3455
- [x] `Atomic_Op` - 4a9476b
- `Thread` (there is a separate issue for this with a 150$ bounty: https://github.com/azerothcore/azerothcore-wotlk/issues/99)

**The list will be replenished**

# Steps
- [x] 1. Update `acelite`, set lib to `STATIC` and disable incorrect fix `std::auto_ptr` #3450
- [x] 2. Rework `Config` #3453 
- [x] 3. Delete `AutoPtr` #3454
- [x] 4. Replace `Ace Atomic` 4a9476b
- [x] 5. Replace `Ace Time` #3455
- [x] 6. Replace `ACE_Method_Request` #3459
- [x] 7. Replace `ACE_Configuration` #4608
- [x] 8. Replace `ACE_Thread_Mutex` | `ACE_GUARD` #4821
- [x] 9. Replace `ACE_Event_Handler` #4877
- [x] 10. Replace `ACE_ASSERT` #4950
- [x] 11. Delete `ACE_Semaphore` #4951
- [x] 12. Delete `ACE_TSS` #5454
- [x] 13. Delete `Future` and `Queue` #5611
- [ ] 14. `The end` #6980 and #5679

**Comment by Mitradis** [comment]
@Winfidonarleyan plz fix last PR.

**Comment by FrancescoBorzi** [comment]
the bounty here is EXCLUDING the Thread part, which has already 120$ in a separate issue: https://github.com/azerothcore/azerothcore-wotlk/issues/99

**Comment by FrancescoBorzi** [comment]
Commits from @namreeb at CMaNGOS might be useful for this task: https://github.com/cmangos/mangos-wotlk/commits?after=b1ad3bb4e616537a167b9abd191a3a55499d7b50+69&author=namreeb

**Comment by abebeos** [comment]
@FrancescoBorzi , could you update the checkboxes?

- [x] Method_Request - #3459
- [ ] Stack_Trace

**Comment by abebeos** [comment]
And additionally, if possible, order the list by expected difficulty (easy first) ?

**Comment by FrancescoBorzi** [comment]
@abebeos done, thanks. I'm not sure about the expected difficulty of the tasks. I'd need to investigate to determine it

**Comment by abebeos** [comment]
> @abebeos done, thanks.

Oh, I meant the whole thing, the "Steps" section is essentially a "Completed" section, but this should be deleted an the information should be moved up into the main list (like the example with "Method_Request").

**Comment by FrancescoBorzi** [comment]
ah yeah right, @Winfidonarleyan what do you think?

**Comment by abebeos** [comment]
> ah yeah right, @Winfidonarleyan what do you think?

It's more or less standard extend the initial list. And any changes of yours can be reversed...

**Comment by abebeos** [comment]
Why removing ace completely?

**Comment by Helias** [comment]
Because it is an old library not maintained anymore afaik and now the modern C++ already supports a lot of feature and functionalities that ACE provide.
It is also a static dependency that we keep in the repository, removing it will give us a lot of benefits and modern way to implement different design pattern and minor features.

**Comment by abebeos** [comment]
Hey, you sound like a salesman now!

Technically, is it really neccessary to strip all(!) of ACE now(!) ?

Can e.g. the config be postponed? Some other stuff not directly available in modern C++?

And shouldn't you possibly migrated away from acs with C17?

In any awy, you need to be faster. WHy delays with things like #3874? Or "Caption Normalization" merge?

Be aware that delays kill motivation to contribute.

re this issue: the original text is not up to date. why do you ask, instead modifying it?

**Comment by Helias** [comment]
You are curious, I think this is a good motivation of contributions.
Anyways, I think that @FrancescoBorzi  and the other developers can give you more technical details about removing ACE :wink: 

But it's something that other communities already did with other software, use modern technologies is always a good thing when you remove old dependencies.

**Comment by Winfidonarleyan** [comment]
**This general part for** #4302

**Comment by Winfidonarleyan** [comment]
I done this, need time for port
https://github.com/WarheadCore/WarheadBand/commit/6ef9e4a732d0c2922484d907affb5faec420f806

**Comment by Winfidonarleyan** [comment]
For test core without `ace` use my custom fork https://github.com/WarheadCore/WarheadBand

**Comment by Kitzunu** [comment]
Soon hehe

**Comment by Winfidonarleyan** [comment]
Yes yes, after 25.06.2021 i start delete full

**Comment by Kitzunu** [comment]
👏

**Comment by FrancescoBorzi** [comment]
congrats @Winfidonarleyan and everyone else who helped with this transition!

**Comment by Winfidonarleyan** [comment]
> congrats @Winfidonarleyan and everyone else who helped with this transition!

Thanks
