### ISSUE TITLE
[EPIC] LBRS - UBRS

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#8961]
List of remaining TODOs for UBRS and LBRS

## General issues

- [x] https://github.com/azerothcore/progression-system/issues/47 (mandatory)
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/8352 (functional)

## Encounter issues
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/611 (mandatory)

## General issues
- [ ] https://github.com/azerothcore/azerothcore-wotlk/issues/8998

## Encounter issues
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/7364
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/8712
- [x] https://github.com/azerothcore/azerothcore-wotlk/issues/7362

**Comment by Kitzunu** [comment]
Imo we should use projects for this instead of opening dull issues

**Comment by FrancescoBorzi** [comment]
> Imo we should use projects for this instead of opening dull issues

we can't afford having 1 project per epic, it would end up with too many projects to look at...

**Comment by Kitzunu** [comment]
It practically works the same way tho.

**Comment by Kitzunu** [comment]
Or milestones

**Comment by Shineslippers** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/9023 instead of https://github.com/azerothcore/azerothcore-wotlk/issues/7364 https://github.com/azerothcore/azerothcore-wotlk/issues/8712 like said @patou01 https://github.com/azerothcore/azerothcore-wotlk/issues/8712#issuecomment-962607790

**Comment by patou01** [comment]
Just added https://github.com/azerothcore/azerothcore-wotlk/issues/9027 , I'm not entirely sure it's an issue because maybe they've been removed at some point, but doubt it.

**Comment by Yehonal** [comment]
> Or milestones

Milestones can't be organization-wide, therefore they can't contain issues from other projects. Which doesn't fits well when to complete a certain EPIC you need to involve more repositories (modules).

Maybe the new project view (in beta) can help organize things a little bit better but let's **Keep It Simple Stupid** for now. Moreover, an EPIC issue can be "discussed", so I'd open it nevertheless to improve the communication

**Comment by Kitzunu** [comment]
What about keeping it in discussions? I just dont want the issues flooded with placeholders/duplicates of issues that already exists.

**Comment by patou01** [comment]
@yehonal, you might want to fetch the remaining issues we've mentioned in comments to the milestone. At least I assume you'd want that. There's a decent amount that have popped up regarding LBRS in the recent days.
